App_Blog/urls.py
from django.urls import path
from . import views

app_name = 'App_Blog'

urlpatterns = [
    path('', views.BlogList.as_view(), name='blog_list'),
    path('write/', views.CreateBlog.as_view(), name='create_blog'),
    path('details/<slug:slug>', views.blog_details, name='blog_details'),
    path('liked/<pk>', views.liked, name='liked_post'),
    path('unliked/<pk>/', views.unliked, name='unliked_post'),
    path('my-blog/', views.MyBlogs.as_view(), name='my_blogs'),
    path('edit-blog/<pk>/', views.UpdateBlog.as_view(), name='edit_blog'),
]

App_Login/urls.py
from django.urls import path
from . import views

app_name = 'App_Login'

urlpatterns = [
    path('signup/', views.sing_up, name='signup'),
    path('signin/', views.login_page, name='signin'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('change-profile/', views.user_change, name='user_change'),
    path('password/', views.pass_change, name='pass_change'),
    path('change-profile-image/', views.add_pro_pic, name='add_pro_pic'),
    path('change-picture/', views.change_pro_pic, name='change_pro_pic'),
]

My_Blog_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_Login.urls')),
    path('blog/', include('App_Blog.urls')),
    path('', views.index, name='index')
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

App_Login/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name='user_profile', on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to='profile_pics')

App_Login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from django.contrib.auth.models import User
from App_Login.models import UserProfile


class SignUpForm(UserCreationForm):
    email = forms.EmailField(label="Email Address", required=True)
    class Meta:
        model = User
        fields = ('username','email','password1','password2')

class UserProfileChange(UserChangeForm):
    class Meta:
        model = User
        fields = ('username','email','first_name','last_name','password')

class ProfilePic(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['profile_pic',]

App_Login/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm,PasswordChangeForm
from django.contrib.auth import login, authenticate, logout
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from App_Login.forms import SignUpForm, UserProfileChange,ProfilePic

# Create your views here.

def sing_up(request):
    form = SignUpForm()
    registered = False
    if request.method == 'POST':
        form = SignUpForm(data=request.POST)
        if form.is_valid():
            form.save()
            registered = True

    dict = {'form':form, 'registered':registered }
    return render(request, 'App_Login/signup.html',context=dict)

def login_page(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

    return render(request,'App_Login/login.html', context={'form':form})

@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('App_Login:signin'))


@login_required
def profile(request):
    return render(request,'App_Login/profile.html', context={})

@login_required
def user_change(request):
    current_user = request.user
    form = UserProfileChange(instance=current_user)
    if request.method == 'POST':
        form = UserProfileChange(request.POST, instance=current_user)
        if form.is_valid():
            form.save()
            form = UserProfileChange(instance=current_user)
    return render(request, 'App_Login/change_profile.html', context={'form':form})

@login_required
def pass_change(request):
    current_user = request.user
    changed = False
    form = PasswordChangeForm(current_user)
    if request.method == 'POST':
        form = PasswordChangeForm(current_user, data=request.POST)
        if form.is_valid():
            form.save()
            changed = True
    return render(request,'App_Login/pass_change.html', context={'form':form,'changed':changed})

@login_required
def add_pro_pic(request):
    form = ProfilePic()
    if request.method == 'POST':
        form = ProfilePic(request.POST, request.FILES)
        if form.is_valid():
            user_obj = form.save(commit=False)
            user_obj.user = request.user
            user_obj.save()
            return HttpResponseRedirect(reverse('App_Login:profile'))
    return render(request,'App_Login/pro_pic_add.html', context={'form':form})

@login_required
def change_pro_pic(request):
    form = ProfilePic(instance=request.user.user_profile)
    if request.method == 'POST':
        form = ProfilePic(request.POST, request.FILES, instance=request.user.user_profile)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('App_Login:profile'))
    return render(request,'App_Login/pro_pic_add.html', context={'form':form})

templates/App_Login/change_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} Chagne User Profile  {% endblock %}


{% block body_block %}
<h2>User Profile Change</h2>
<form method="post">
  {{ form|crispy }}
  {% csrf_token %}
  <button type="submit" class="btn btn-primary btn-sm" >Change</button>

</form>


{% endblock %}

templates/App_Login/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} Login Page  {% endblock %}


{% block body_block %}
<h2>Login Your Account</h2>
<form method="post">
  {{ form|crispy }}
  {% csrf_token %}
  <button type="submit" class="btn btn-primary btn-sm" >Login</button>

</form>


{% endblock %}

templates/App_Login/pass_change.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} Password Change Page  {% endblock %}

{% block body_block %}

{% if changed %}
<div class="alert alert-success">
  Password Change Successfully
</div>
{% endif %}

<h2>Password Change</h2>
<form method="post">
  {{ form|crispy }}
  {% csrf_token %}
  <button type="submit" class="btn btn-primary btn-sm">Change</button>

</form>


{% endblock %}

templates/App_Login/pro_pic_add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} Profile picture update  {% endblock %}


{% block body_block %}
<h2>Add Your Profile Picture</h2>
<form method="post" enctype="multipart/form-data">
  {{ form|crispy }}
  {% csrf_token %}
  <button type="submit" class="btn btn-primary btn-sm" >Add Picture</button>

</form>


{% endblock %}

templates/App_Login/profile.html
{% extends 'base.html' %}
{% block title %} Profile Page  {% endblock %}


{% block body_block %}
<h2>Your Profile </h2>
{% if user.user_profile %}
<img src="/media/{{user.user_profile.profile_pic}}" class="rounded-circle" width="120px">
<br><br>
<a href="{% url 'App_Login:change_pro_pic' %}" class="btn btn-info btn-sm">Change Profile Pic</a>


{% else %}
<img src="/media/download.jpg" class="rounded-circle" width="120px">
<br>
<a href="{% url 'App_Login:add_pro_pic' %}" class="btn btn-info btn-sm">Change Profile Pic</a>
{% endif %}

<p>Username : {{ user.username }}</p>
<p>Email : {{ user.email }}</p>
<p>Name : {{ user.first_name }} {{ user.last_name }}</p>

<br>
<a href="{% url 'App_Login:user_change' %}" class="btn btn-warning btn-sm">Change Profile Info</a>

{% endblock %}

templates/App_Login/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% crispy form %}
{% block title %} Create New Account  {% endblock %}

{% block body_block %}
{% if registered %}
<div class="alert alert-success">
  Account Created Successfully <a href="{% url 'App_Login:signin' %}">Login Here </a>
</div>
{% else %}

<h2> Create New Account </h2>
<form method="post">
  {{ form|crispy }}
  {% csrf_token %}
  <button type="submit" class="btn btn-success btn-sm">Create Account</button>
</form>
<br>
<p>Already have an account? <a href="{% url 'App_Login:signin' %}">Login Here</a></p>

{% endif %}
{% endblock %}