App_Blog/urls.py
from django.urls import path
from . import views

app_name = 'App_Blog'

urlpatterns = [
    path('', views.BlogList.as_view(), name='blog_list'),
    path('write/', views.CreateBlog.as_view(), name='create_blog'),
    path('details/<slug:slug>', views.blog_details, name='blog_details'),
    path('liked/<pk>', views.liked, name='liked_post'),
    path('unliked/<pk>/', views.unliked, name='unliked_post'),
    path('my-blog/', views.MyBlogs.as_view(), name='my_blogs'),
    path('edit-blog/<pk>/', views.UpdateBlog.as_view(), name='edit_blog'),
]

App_Login/urls.py
from django.urls import path
from . import views

app_name = 'App_Login'

urlpatterns = [
    path('signup/', views.sing_up, name='signup'),
    path('signin/', views.login_page, name='signin'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('change-profile/', views.user_change, name='user_change'),
    path('password/', views.pass_change, name='pass_change'),
    path('change-profile-image/', views.add_pro_pic, name='add_pro_pic'),
    path('change-picture/', views.change_pro_pic, name='change_pro_pic'),
]

My_Blog_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_Login.urls')),
    path('blog/', include('App_Blog.urls')),
    path('', views.index, name='index')
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
    <title>
      {% block title  %}
        Blogs Page
      {% endblock %}

    </title>
  </head>
  <body>

    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'index' %}">Home</a>
          </li>

          {% if user.is_authenticated %}
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'App_Blog:create_blog' %}">Write Blog</a>
          </li>

          <li class="nav-item active">
            <a class="nav-link" href="{% url 'App_Login:logout' %}">Logout</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'App_Login:profile' %}">Profile</a>
          </li>
          {% else %}

          <li class="nav-item active">
            <a class="nav-link" href="{% url 'App_Login:signup' %}">Sign Up</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'App_Login:signin' %}">Login</a>
          </li>
          {% endif %}
        </ul>
       {% if user.is_authenticated %}
        <div class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
            {{ user.username }}
          </a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="{% url 'App_Blog:my_blogs' %}">My Blog</a>
            <a class="dropdown-item" href="{% url 'App_Login:profile' %}">Your Profile</a>
            <a class="dropdown-item" href="{% url 'App_Login:logout' %}">Logout</a>

        </div>
      </div>
      {% endif %}
    </nav>


    <div class="container" style="padding-top:20px">
      {% block body_block %}

      {% endblock %}
    </div>






    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>