App_Blog/urls.py
from django.urls import path
from . import views

app_name = 'App_Blog'

urlpatterns = [
    path('', views.BlogList.as_view(), name='blog_list'),
    path('write/', views.CreateBlog.as_view(), name='create_blog'),
    path('details/<slug:slug>', views.blog_details, name='blog_details'),
    path('liked/<pk>', views.liked, name='liked_post'),
    path('unliked/<pk>/', views.unliked, name='unliked_post'),
    path('my-blog/', views.MyBlogs.as_view(), name='my_blogs'),
    path('edit-blog/<pk>/', views.UpdateBlog.as_view(), name='edit_blog'),
]

My_Blog_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_Login.urls')),
    path('blog/', include('App_Blog.urls')),
    path('', views.index, name='index')
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

App_Blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Blog(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post_author')
    blog_title = models.CharField(max_length=264, verbose_name="Put a Title")
    slug = models.SlugField(max_length=264, unique=True)
    blog_content = models.TextField(verbose_name="What is on your mind?")
    blog_image = models.ImageField(upload_to='blog_images', verbose_name="Blog Image")
    publish_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-publish_date']

    def __str__(self):
        return self.blog_title

class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='blog_comment')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_comment')
    comment = models.TextField()
    comment_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-comment_date']

    def __str__(self):
        return self.comment



class Likes(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='liked_blog')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='liker_user')

App_Blog/forms.py
from django import forms
from App_Blog.models import Blog, Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment',)

App_Blog/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.views.generic import CreateView, UpdateView, ListView, DetailView, TemplateView, DeleteView
from App_Blog.models import Blog, Comment, Likes
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
import uuid
from App_Blog.forms import CommentForm

# Create your views here.

class MyBlogs(LoginRequiredMixin,TemplateView):
    template_name = 'App_Blog/my_blogs.html'


class UpdateBlog(LoginRequiredMixin, UpdateView):
    model = Blog
    fields = ('blog_title','blog_content','blog_image')
    template_name = 'App_Blog/edit_blog.html'

    def get_success_url(self, **kwargs):
        return reverse_lazy('App_Blog:blog_details', kwargs={'slug':self.object.slug})



class BlogList(ListView):
    context_object_name = 'blogs'
    model = Blog
    template_name = 'App_Blog/blog_list.html'

class CreateBlog(LoginRequiredMixin,CreateView):
    model = Blog
    template_name = 'App_Blog/create_blog.html'
    fields = ('blog_title','blog_content','blog_image')

    def form_valid(self, form):
        blog_obj = form.save(commit=False)
        blog_obj.author = self.request.user
        title = blog_obj.blog_title
        blog_obj.slug = title.replace(" ","-") + "-" + str(uuid.uuid4())
        blog_obj.save()
        return HttpResponseRedirect(reverse('index'))


def blog_details(request, slug):
    blog = Blog.objects.get(slug=slug)
    comment_form = CommentForm()
    already_liked = Likes.objects.filter(blog=blog, user=request.user.id)
    if already_liked:
        liked = True
    else:
        liked = False
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.user = request.user
            comment.blog = blog
            comment.save()
            return HttpResponseRedirect(reverse('App_Blog:blog_details', kwargs={'slug':slug}))

    return render(request, 'App_Blog/blog_details.html', context={'blog':blog,'comment_form':comment_form,'liked':liked})

@login_required
def liked(request, pk):
    blog = Blog.objects.get(pk=pk)
    user = request.user
    already_liked = Likes.objects.filter(blog=blog, user=user)
    if not already_liked:
        liked_post = Likes(blog=blog, user=user)
        liked_post.save()
    return HttpResponseRedirect(reverse('App_Blog:blog_details', kwargs={'slug':blog.slug}))

@login_required
def unliked(request, pk):
    blog = Blog.objects.get(pk=pk)
    user = request.user
    already_liked = Likes.objects.filter(blog=blog, user=user)
    already_liked.delete()
    return HttpResponseRedirect(reverse('App_Blog:blog_details', kwargs={'slug':blog.slug}))

templates/App_Blog/blog_details.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} BLOG Details  {% endblock %}

{% block body_block %}

<div class="row">
  <div class="col-sm-6">
    <h2>{{ blog.blog_title }}</h2>
    <h4>Posted By : {{ blog.author }}</h4>
    <i><h6>Published On:  {{ blog.publish_date }}</h6></i>
    <i><h6>Updated On:  {{ blog.update_date }}</h6></i>
    <h6>{{ blog.liked_blog.count }} Likes | {{ blog.blog_comment.count }} Comments</h6>
  </div>

  <div class="col-sm-6">
    <img src="/media/{{blog.blog_image}}" width="100%">
  </div>
   {{ blog.blog_content|linebreaks }}
</div>

<hr>
{% if not liked %}
<a href="{% url 'App_Blog:liked_post' pk=blog.pk %}">
<i class="fa fa-thumbs-o-up fa-2x"></i>
</a>
{% else %}
<a href="{% url 'App_Blog:unliked_post' pk=blog.pk %}">
<i class="fa fa-thumbs-o-down fa-2x"></i>
</a>
{% endif %}




 <div class="row">
   <div class="col-sm-6">
     <h5>Comments:</h5>
     {% for comment in blog.blog_comment.all %}
     <p><a href="#">{{ comment.user }}</a></p>
     <b>{{ comment.comment }}</b><br>
     <h6><i>{{comment.comment_date}}</i></h6>
     {% endfor %}
   </div>


   <div class="col-sm-6">
     <form method="post">
       {{ comment_form|crispy }}
       {% csrf_token %}
       <button type="submit" class="btn btn-primary btn-sm">Comment</button>

     </form>
   </div>

 </div>

<br><br><br>


{% endblock %}

templates/App_Blog/blog_list.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block title %} Home  {% endblock %}

{% block body_block %}

{% for blog in blogs %}
<h2> {{ blog.blog_title }}</h2>
<h6><i>{{ blog.publish_date }}</i></h6>

<div class="row">
  <div class="col-sm-4">
    <img src="/media/{{blog.blog_image}}" alt="{{ blog.blog_title }}" title="{{ blog.blog_title }}" width="100%">
  </div>


  <div class="col-sm-8">
<p>{{ blog.blog_content|range_filter|linebreaks }}
   <a href="{% url 'App_Blog:blog_details' slug=blog.slug %}">Read More</a>
</p>
<h6>Posted By: <a href="#">{{ blog.author }}</a></h6>
<h6>{{ blog.liked_blog.count }} Likes | {{ blog.blog_comment.count }} Comments</h6>
  </div>

</div>






{% endfor %}
{% endblock %}

templates/App_Blog/create_blog.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} Create Blog  {% endblock %}

{% block body_block %}
<h2>Write Your Blog Here:</h2>
<form method="post" enctype="multipart/form-data">
 {{ form|crispy }}
 {% csrf_token %}
 <button type="submit" class="btn btn-success btn-sm" >Publish</button>
</form>
<br><br><br>
{% endblock %}

templates/App_Blog/edit_blog.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} Edit Blog  {% endblock %}

{% block body_block %}

{% if blog.author == user %}

<form method="post" enctype="multipart/form-data">
  {{ form|crispy }}
  {% csrf_token %}
  <button type="submit" class="btn btn-info btn-sm">Update</button>
</form>
{% else %}
<p> You are not allowed to vie this page </p>

{% endif %}

{% endblock %}

templates/App_Blog/my_blogs.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block title %} My Blog  {% endblock %}

{% block body_block %}

  {% for blog in user.post_author.all %}
<h3>{{ blog.blog_title }}</h3>
<h6>{{ blog.publish_date }}</h6>

<div class="row">
  <div class="col-sm-4">
    <img src="/media/{{blog.blog_image}}" width="100%">
  </div>

  <div class="col-sm-8">
    <p>{{ blog.blog_content|range_filter|linebreaks }}
       <a href="{% url 'App_Blog:blog_details' slug=blog.slug %}">Read More</a>
    </p>
    <h6>{{ blog.liked_blog.count }} Likes | {{ blog.blog_comment.count }} Comments</h6>

  </div>
</div>
<hr>
<a href="{% url 'App_Blog:edit_blog' pk=blog.pk %}" class="btn btn-info btn-sm">Edit</a>

  {% endfor %}



{% endblock %}